# Generated by Django 6.0.2 on 2026-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
