# Generated by Django 6.0.2 on 2026-02-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_wholesale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
